apiVersion: apps/v1
kind: Deployment
metadata:
  name: pullrequestcheckservice-deployment
  namespace: pullrequestcheck
  labels:
    app: pullrequestcheckservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pullrequestcheckservice
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pullrequestcheckservice
    spec:
      containers:
      - name: azuredevops-pullrequestcheckservice
        image: {dockerRegistry}/azuredevops.pullrequestcheckservice:latest
        env:
        - name: DevOpsServerConfiguration__URL
          value: "{URL}"
        - name: DevOpsServerConfiguration__Collection
          value: "{Collection}"
        - name: DevOpsServerConfigurationr__AccessToken
          value: "{PAT}"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 10
      imagePullSecrets:
      - name: regcred
