apiVersion: v1
kind: Service
metadata:
  name: pullrequestcheck-service
  namespace: pullrequestcheck
  labels:
    app: pullrequestcheckservice
spec:
  type: NodePort
  ports:
  - port: 8080 # container port
    targetPort: 8080 # container port
    nodePort: 30031 # external port
    protocol: TCP
  selector:
    app: pullrequestcheckservice